### ISSUE TITLE
Events remain perpetually in In Progress

### ISSUE THREAD

**Issue by marcos-acosta** [awslabs/aws-media-replay-engine#6]
Hello!

MRE Version: 2.5.1

I am prototyping an MRE solution, and noticed something that I'm not sure is expected behavior. My input source for my Event is an S3 bucket, and MRE successfully processes videos that I add to that bucket (i.e. passes through Featurer, Segmenter, Labeler). The status for that Event remains `In Progress` even after it finishes processing every available video in the bucket, which could make sense since it is always waiting for new input.

However, I noticed that when I create a Replay Request for that Event, it remains stuck in `Queued`, and would not progress to `In Progress` unless I went into DynamoDB and manually changed the Event's status from `In Progress` to `Completed`.

Could you explain what the expected behavior is here? Thank you!

**Comment by aravindkaws** [comment]
Hi Marcos,
Thanks for reaching out. MRE supports the ability to create CatchUp or NonCatchup replays. If your requirement is to have MRE continuously generate replays when an event is in progress, ensure the "CatchUp" setting during replay creation is enabled. You should see the Replay status change to "In Progress". If the requirement is to just create a replay after an event is done (Event status is Completed) the "Catchup" setting should be disabled. 

In both cases, whenever an event is marked "Complete", a replay is triggered which is why you see the replay status change to "In Progress". Hope this explains it.

**Comment by aravindkaws** [comment]
Closing this issue. Please reopen if you are running into similar problems with MRE v2.6.0
