### ISSUE TITLE
Question regarding MRE use case + synchronizing plugins

### ISSUE THREAD

**Issue by marcos-acosta** [awslabs/aws-media-replay-engine#8]
Hello!

We are planning on using MRE to detect football highlights, and a few of our brainstormed feature detectors would rely on future knowledge to determine the importance of a play. For example:
1. The length of replays after the play (more replays indicate more exciting play)
2. Score (because of the "Touchdown" banner, the updated score doesn't appear until the play has been over for a few seconds)

We were wondering if it would be possible to make predictors of this type. For example, if we have one featurer that extracts the score of every frame (if it exists), would a second featurer be able to look a few seconds ahead to determine if the current play is responsible for that change in score? Or can featurers only access results from other featurers up to that chunk?

In general, how does MRE synchronize featurers and the segmenter as new chunks are arriving?

Thank you for your guidance!

**Comment by araviraj-aws** [comment]
Hi @marcos-acosta! In MRE, the synchronization of segmenter and featurers happens during Replay creation. That is, once you create a replay by choosing weights for different features, MRE will then query the PluginResult DynamoDB table to look for all the segments which contain the features selected during the replay creation. Because these features are typically outputted by the featurer plugins that execute independent of the segmenter plugin, the Replay Engine basically uses the "Start" time associated with these features to verify if a given feature is present within a segment or not (segment Start <= feature Start <= segment End). Once it finds a list of segments and associated features, it then uses the weights given during replay creation to each of these features to calculate an overall score for a segment and then decide whether or not to include that segment in the replay. This whole process happens every time a new segment is identified by MRE (if it's a catchup replay) or once at the end of the event after all the segments have been identified (if it's a non-catchup replay).

Now, to answer your other question on whether it's possible to "look ahead" in a featurer plugin - currently it's not possible to do so since there are no capabilities available (yet) in MRE to support this feature out-of-the-box. However, given you're looking to determine the importance of a play based on the future data, a possible workaround for this could be to "look back" once the future data arrives and then modify the play that happened prior to that. In order to implement this workaround, you would probably need to make use of the get_segment_state MRE dataplane API to get the last stored segment, figure out if it's important or not using the current chunk data (that is, if the instant replay found in the current chunk is long or not), and if the prior segment is deemed important, then store it again in MRE using the same Start and End time (now with additional metadata included to denote its importance). In addition to this, you may also need to make the featurer plugin that's detecting scores as the dependent plugin of the segmenter (so that the segmenter now knows what the featurer detected for that chunk) and include the Start, End, and other relevant metadata of segment N-1 when persisting segment N in cases where segment N is partial (that is, only Start was found with no End). This is to handle certain scenarios where a segment could span across multiple chunks resulting in get_segment_state giving you partial segment as the last identified segment.

**Comment by marcos-acosta** [comment]
Hi @araviraj-aws! Thanks so much for the detailed response, I really appreciate it. I have a couple, smaller questions based on your answer that I could use some clarification on, if you don't mind.

1. You mention that when creating a Replay, MRE looks through the feature results that occur between each segment `Start` and `End`. How does MRE handle the fact that the desired feature has multiple values within time frame? Does the criteria only need to be met once within the segment to be weighted?
2. You suggested re-storing previous segments with `additional metadata included to denote its importance` if we retroactively determine a previous segment be more important. But as you said, when generating Replays, MRE only looks at featurer results within the `Start` and `End` time of each segment, so what information could we add to the segment itself that MRE would use in the Replay generation step?

And three more related questions:

3. Looking through the sample plugin [`SegmentByScene`](https://github.com/aws-samples/aws-media-replay-engine-samples/blob/main/source/mre-plugin-samples/Plugins/SegmentByScene/SegmentByScene.py#L160) in `aws-media-replay-engine-samples`, I noticed that partial segments are stored in the dataplane by storing an incomplete segment with a `Start` but no `End`, and when it finds the `End` in a later chunk, it stores a new segment with the same `Start` from the incomplete segment and the newly found `End`. Is my reading of the code correct? Is the incomplete segment ignored by MRE?
4. The UI seems to imply that features chosen as weights for Replay creation must be binary features (it shows `| true` and `| false` after each featurer output attribute when setting the weights). Is that correct?
5. To emulate a live video source, we've been adding 25-second `.mp4` video chunks to an S3 bucket. We set timecode source to `NOT_EMBEDDED`, but noticed that MRE doesn't seem to work properly, as it uses the PTS time of the first keyframe as the start time of each chunk, and so for example it thinks the second chunk starts at `t=3.883` when it really occurs 25 seconds after the first chunk. Because of this, the segmenter can't work properly. Do you have advice for how to work with this? Or is this not expected behavior?

Thank you again for your patience with our questions!
-Marcos

**Comment by marcos-acosta** [comment]
Hi @araviraj-aws, thank you so much again for your detailed responses! Two last quick questions before I'm happy to close the issue:
1. Within a featurer, is it possible to read its own plugin results on a previous chunk? Or is "looking across chunks" only possible in segmenters by design?
2. I have a featurer that uses Custom Labels to determine the scene type (e.g. in play, down time, replay, etc.). I would like the segmenter to create segments by grouping together long stretches of one type of detection. However, doing this requires some kind of state persistence to remember what type of scene to include in the segment and know when to end. E.g. if we find the start of a replay at the end of one chunk, it wouldn't be enough to know that the segment state is `Start` in the next chunk, it must also know that it's looking for more replay frames and to end the segment when it starts seeing non-replay scene types. Is it possible to persist arbitrary state across chunks like this? Should I create an output attribute from the segmenter with that information, and then read it in within the segmenter itself?

Thanks again!

**Comment by araviraj-aws** [comment]
Hi @marcos-acosta !

1. There's currently no API available in the data plane that lets a featurer plugin read its own results from a previous chunk. However, it doesn't mean this is not possible to achieve. In your featurer plugin, you can query the PluginResult DynamoDB table directly using the `PK_ChunkNumber-index` GSI with `<program>#<event>#<featurer_plugin_name>` as the partition key and `<chunk_number>` of the previous chunk as the sort key to get the results.

2. When you ask for the segment state using the `get_segment_state()` API, it not only returns the last segment state (which is either `Start` or `End`) but also returns the last stored segment itself (which is nothing but the actual DDB item). So, if you persist the scene type information as an additional attribute (key) when storing the segment, you could then read them the next time you get the segment state and take action accordingly. Let me know if this answers your question or if I totally misinterpreted your use case.

Thanks!

**Comment by marcos-acosta** [comment]
Great, those perfectly answer my questions. Thank you!
